name: Deployment

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production
    concurrency: production
    steps:
      - name: Branch name
        id: branch_name
        run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build binary
        env:
          GOOS: linux
          GOARCH: arm64
        run: |
          go mod vendor
          go build -o bin/dns-api ./cmd/api.go

      - name: Deploy
        env:
          DEPLOYMENT_HOST: ${{ secrets.DEPLOYMENT_HOST }}
          DEPLOYMENT_USER: ${{ secrets.DEPLOYMENT_USER }}
          DEPLOYMENT_SSH_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_SSH_PRIVATE_KEY }}
          DEPLOYMENT_SSH_KNOWN_HOSTS: ${{ secrets.DEPLOYMENT_SSH_KNOWN_HOSTS }}
          RELEASES: /var/www/dns-api/releases
        run: |
          mkdir -p ~/.ssh
          echo "${DEPLOYMENT_SSH_PRIVATE_KEY}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${DEPLOYMENT_SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
          rsync -r bin ${DEPLOYMENT_USER}@${DEPLOYMENT_HOST}:${RELEASES}/${SOURCE_TAG}
          ssh ${DEPLOYMENT_USER}@${DEPLOYMENT_HOST} " \
            systemctl stop dns-api && \
            cd /var/www/dns-api && \
            ln -sfn releases/${SOURCE_TAG} current && \
            chmod +x current/bin/dns-api && \
            chown -R www-data:www-data current && \
            chown -R www-data:www-data releases/${SOURCE_TAG} && \
            systemctl start dns-api"
